<?php

namespace App\Models;

use MongoDB\Laravel\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Submission extends Model
{
    use HasFactory;

    protected $connection = 'mongodb';
    protected $collection = 'submissions';

    protected $fillable = [
        'exam_id',
        'candidate_id',
        'answers', // array of objects: [['question_id' => '...', 'selected_option' => '...', 'code_submitted' => '...', 'language' => '...', 'is_correct' => true]]
        'score',
        'duration_taken_seconds',
        'status', // in_progress, submitted, graded
        'ai_feedback', // text summary generated by AI
        'cheating_score', // overall score 0 to 100% computed from cheating events
    ];

    protected $casts = [
        'answers' => 'array',
        'score' => 'float',
        'duration_taken_seconds' => 'integer',
        'cheating_score' => 'integer',
    ];

    /**
     * Relationships
     */
    public function exam()
    {
        return $this->belongsTo(Exam::class, 'exam_id');
    }

    public function candidate()
    {
        return $this->belongsTo(User::class, 'candidate_id');
    }

    public function cheatingEvents()
    {
        return $this->hasMany(CheatingEvent::class, 'submission_id');
    }

    public function proctorLogs()
    {
        return $this->hasMany(ProctorLog::class, 'submission_id');
    }
}
